# Generated by Django 3.2.8 on 2021-10-23 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=3000)),
                ('cateogry', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('time', models.TimeField()),
                ('dates', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.CharField(max_length=3000)),
                ('dates', models.DateField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.date')),
            ],
        ),
    ]
