# Generated by Django 3.2.6 on 2021-10-29 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='dates',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='time',
            field=models.TimeField(null=True, verbose_name='Time of Event'),
        ),
        migrations.RemoveField(
            model_name='date',
            name='user',
        ),
        migrations.AddField(
            model_name='date',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
