# Generated by Django 3.2.6 on 2021-10-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='dates',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='time',
            field=models.TimeField(null=True, verbose_name='Time of Event'),
        ),
    ]
