# Generated by Django 3.2.6 on 2021-10-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='decription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='date',
            name='cateogry',
        ),
        migrations.AddField(
            model_name='date',
            name='category',
            field=models.CharField(choices=[('AD', 'Affordable Dates'), ('SO', 'Special Occasions'), ('AV', 'Adventurous Dates')], default='AD', max_length=2),
        ),
        migrations.AlterField(
            model_name='date',
            name='dates',
            field=models.DateField(verbose_name='Date of Event'),
        ),
        migrations.AlterField(
            model_name='date',
            name='time',
            field=models.TimeField(verbose_name='Time of Event'),
        ),
        migrations.AlterField(
            model_name='review',
            name='dates',
            field=models.DateField(verbose_name='Date of Review'),
        ),
    ]
