# Generated by Django 3.2.6 on 2021-10-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211025_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=3000)),
                ('location', models.CharField(max_length=250)),
                ('time', models.TimeField(verbose_name='Time of Event')),
                ('dates', models.DateField(verbose_name='Date of Event')),
                ('price', models.DecimalField(decimal_places=2, max_digits=400)),
            ],
        ),
        migrations.AddField(
            model_name='date',
            name='my_list',
            field=models.ManyToManyField(to='main_app.MyList'),
        ),
    ]
